### ISSUE TITLE
tf-idz.npz not found

### ISSUE THREAD

**Issue by TheGiantDad** [alecokas/swahili-text-gcn#43]
I have followed all the steps on the readme file and when i try to test the baseline model i get this error "FileNotFoundError: [Errno 2] No such file or directory: 'results\\Baseline_results\\preproc\\tf-idf.npz". I'm running it on windows I don't know if that matters.

**Comment by alecokas** [comment]
Hi @TheGiantDad. Yes, there's a good chance this is a Windows specific issue to do with the handling of relative paths. We only plan to support Linux and MacOS for this repo. I'll make that clear in the README.

**Comment by alecokas** [comment]
I'd need a little more context to address this issue more thoroughly. If this is a Windows specific case, I suspect that forking and making minor path modifications would be trivial.

**Comment by TheGiantDad** [comment]
Okay so these are the commands i used:

python src/create_dataset.py Datos_descargados
python src/generate_stemming_map.py \ --results-dir Datos_preprocesados  --input-data-dir  Datos_descargados
python src/train_baseline.py Baseline_results  --input-data-dir Datos_preprocesados --stemmer-path Datos_preprocesados/stemming/stemming_cleaned.json --model tf-idf

The error i get is this:
Load tf-idf data...
Traceback (most recent call last):
  File "src/train_baseline.py", line 190, in <module>
    main(args)
  File "src/train_baseline.py", line 106, in main
    input_features, labels = load_vectorized_data(preproc_dir, args.model)
  File "D:\desktop\swahili-text-gcn-master\src\baselines\vectorizers.py", line 75, in load_vectorized_data
    data = load_npz(os.path.join(preproc_dir, f'{vectorizer_name}.npz'))
  File "D:\Windows\programas\Anaconda3\envs\GCN\lib\site-packages\scipy\sparse\_matrix_io.py", line 123, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "D:\Windows\programas\Anaconda3\envs\GCN\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'results\\Baseline_results\\preproc\\tf-idf.npz'

I have check the code and the problem is that the function "load_vectorized_data" is trying to open a file that is not created, there is a function that can create it i believe but it isn't called, by the way this problem also appears in the other baselines methods. 

I'll set up a linux environment in the mean time, thanks for your help.

**Comment by alecokas** [comment]
Your problem might be that you need to re-run the stemming map generation script (`python src/generate_stemming_map.py \ --results-dir Datos_preprocesados --input-data-dir Datos_descargados`) a number of times until there are no more words to add. Once all words are added, then the files you need are written to disk. We can have a look into making this an easier process for you.

**Comment by TheGiantDad** [comment]
Ok I'm try that, but it says the vocab is 197167 words long and adding 10000 takes about 3 hours or so it says, is this normal?

**Comment by alecokas** [comment]
Yeah, that's unfortunately not too surprising to me. This is a result of the ongoing under-representation of Swahili in NLP software tools. 
If you can limit your vocabulary size, you absolutely should :)

**Comment by TheGiantDad** [comment]
Okay so, the program won't create the .npz file until all the words are added, but I can limit the vocabulary somehow (I assume to not use more words that my dataset uses). How can I do that? I'm using the Swahili : News Classification Dataset by the way.

**Comment by alecokas** [comment]
If you have a look at the CLI for that script, you'll see a `--count-threshold` parameter which can be used to prune the vocabulary. In our work we have that threshold set to 2.

**Comment by TheGiantDad** [comment]
Okay so, after testing that command in both windows and linux there are some things i found that might be useful:
-It does not generate that npz file so my next step will be to generate the whole vocabulary (it will take long but i haven't got another idea)
-The python version must be exactly 3.6.9 because otherwise it will ask for the version 0.8 of dataclasses which at least in later version of python is only available the 0.6 (which as far as I tried the code works the same)
-In the requirements txt the line "pkg-resources==0.0.0" must be deleted or else pip will not work

**Comment by alecokas** [comment]
Thanks for coming back to us on this. Let me address your points:

> -It does not generate that npz file so my next step will be to generate the whole vocabulary (it will take long but i haven't got another idea)

One can only generate the preprocessed results after completing the process of building the stemming map

> -The python version must be exactly 3.6.9 because otherwise it will ask for the version 0.8 of dataclasses which at least in later version of python is only available the 0.6 (which as far as I tried the code works the same)

It makes sense that the exact packages are tied to the exact version of Python - I'll make that more clear

> -In the requirements txt the line "pkg-resources==0.0.0" must be deleted or else pip will not work

This is a good point - I'll fix that

> -You must add at least once the line import nltk nltk.download('punkt') or else when you try to generate the stemming map it will not work

This too is a good point - I can add an extra step for this

**Comment by TheGiantDad** [comment]
I bring bad news, i think the stemming map is generated however I get the same "npz file not found" error when i try to test the baseline methods. The output of the `generating_stemming_map` command was the following:
`Number of words to add: 0
First pass cleaned and stemmed vocab_counts...
Creating vocab with word counts...
Second pass at cleaning the stemming vocab_counts...`

**Comment by alecokas** [comment]
I guess the obvious thing to check is whether the file is successfully created after generating the stemming map? Again it is difficult to give specific advice without more information.

You definitely don't need 10 TB to train the GCN models presented in our paper. You might want to have a look at the adjacency matrix dimensions, and the number of documents, and vocabulary size.

**Comment by TheGiantDad** [comment]
Okay, solved it, diving in the code i realised it was just a confusion with names, I was giving the` --input-data-dir` parameter the name of the preprocessing folder instead of the name of the downloaded data (the one that create_dataset.py generates).
However i found something interesting, if you test one baseline model, the others you test after will generate some sort of `tf-idz.npz not found` error. 
This is because of this block of code:
```
if not os.path.isdir(preproc_dir):
            os.makedirs(preproc_dir, exist_ok=True)
            build_vectorizer_from_df(
                vectorizer_name=args.model,
                save_dir=preproc_dir,
                df_path=os.path.join(RES_DIR, args.input_data_dir, 'dataset.csv'),
                stemming_map_path=os.path.join(RES_DIR, args.stemmer_path),
                text_column='document_content',
                label_column='document_type',
            )
```
I get the part that if the baseline results folder is not created, you need to create it, however if the folder is already created you won't build the vectorizer, and so the famous .npz file won't be generated. So i just solved it like this and it works
```
if not os.path.isdir(preproc_dir):
            os.makedirs(preproc_dir, exist_ok=True)
build_vectorizer_from_df(
    vectorizer_name=args.model,
    save_dir=preproc_dir,
    df_path=os.path.join(RES_DIR, args.input_data_dir, 'dataset.csv'),
    stemming_map_path=os.path.join(RES_DIR, args.stemmer_path),
    text_column='document_content',
    label_column='document_type',
)
```

**Comment by alecokas** [comment]
Glad to see that you found your issue there @TheGiantDad!

Regarding the change you made, it seems to me that there should not be a scenario where one has already created a the preprocessed document vectors but not the folder to store them into, so I'm not sure why you would want this change. That being said, if it makes sense for your experimental set up then that's great 😁.

Closing this issue as it seems to have all been resolved.
